const fs = require('fs');
let c = fs.readFileSync('server.ts', 'utf8');
const c1 = c.indexOf('const fallback = { id: \"PLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5\"');
const c2 = c.indexOf('exploreCache = { data, timestamp: Date.now() } as any;', c1) + 54;
if(c1 > -1 && c2 > -1){
  const repl1 = '\n    const createFb = (id, title, imgVid) => ({ id, title, artist: \"YouTube Mix\", duration: \"Playlist\", url: \`https://www.youtube.com/playlist?list=\`, thumbnail: \`https://i.ytimg.com/vi//mqdefault.jpg\`, isPlaylist: true, subType: \"playlist\" });\n    if (data.trending.length === 0) data.trending.push(createFb(\"PL4fGSI1pDJn6O1LS0XSdF3RyO0Rq_LDeI\", \"Top Tendencias\", \"4Lz0_SPDoqo\"));\n    if (data.dailyTop.length === 0) data.dailyTop.push(createFb(\"PLx0sYbCqOb8TBPRdmBHs5Iftvv9CB5eXf\", \"Lo Más Nuevo\", \"yebNIHKAC4A\"));\n    if (data.top100.length === 0) data.top100.push(createFb(\"PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i\", \"Top 100 Popular\", \"mTQ_b9kQ6ko\"));\n    if (data.workout.length === 0) data.workout.push(createFb(\"PLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5\", \"Gym Motivation\", \"IZ36b3q1elI\"));\n    if (data.focus.length === 0) data.focus.push(createFb(\"PLOzDu-MXXLliO9fBelCGIawp_EN2kO-dE\", \"Focus & Relax\", \"jGflUbPQfW8\"));\n    if (data.trends.length === 0) data.trends.push(createFb(\"PLxA687tYuMWi8OUus77n7Ziq1j0yL0gGz\", \"Novedades\", \"ru0K8uYEZWw\"));\n    if (data.latin.length === 0) data.latin.push(createFb(\"PLYyq1j1v4R5R20X-bepkF5V66hBWe1a-r\", \"Ritmos Latinos\", \"C7vfCJTQ-rw\"));\n    if (data.party.length === 0) data.party.push(createFb(\"PL7NXvXjIf-gGqSsswXm7-N0BsiW61wJzB\", \"Party Mix\", \"n6N1_sxlBU8\"));\n    exploreCache = { data, timestamp: Date.now() } as any;';
  c = c.substring(0, c1) + repl1 + c.substring(c2);
}
const c3 = c.indexOf('const fallback = { id: \"PLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5\"', c1 > -1 ? c1+100 : 0);
const c4 = c.indexOf('res.json({ trending: [fallback]', c3);
const c5 = c.indexOf(';', c4) + 1;
if(c3 > -1 && c5 > -1){
  const repl2 = '\n    const createFb = (id, title, imgVid) => ({ id, title, artist: \"YouTube Mix\", duration: \"Playlist\", url: \`https://www.youtube.com/playlist?list=\`, thumbnail: \`https://i.ytimg.com/vi//mqdefault.jpg\`, isPlaylist: true, subType: \"playlist\" });\n    res.json({\n      trending: [createFb(\"PL4fGSI1pDJn6O1LS0XSdF3RyO0Rq_LDeI\", \"Top Tendencias\", \"4Lz0_SPDoqo\")],\n      dailyTop: [createFb(\"PLx0sYbCqOb8TBPRdmBHs5Iftvv9CB5eXf\", \"Lo Más Nuevo\", \"yebNIHKAC4A\")],\n      top100: [createFb(\"PL4fGSI1pDJn6puJdseH2Rt9sMvt9E2M4i\", \"Top 100 Popular\", \"mTQ_b9kQ6ko\")],\n      workout: [createFb(\"PLw-VjHDlEOgs658kAHR_LAaILBXb-s6Q5\", \"Gym Motivation\", \"IZ36b3q1elI\")],\n      focus: [createFb(\"PLOzDu-MXXLliO9fBelCGIawp_EN2kO-dE\", \"Focus & Relax\", \"jGflUbPQfW8\")],\n      trends: [createFb(\"PLxA687tYuMWi8OUus77n7Ziq1j0yL0gGz\", \"Novedades\", \"ru0K8uYEZWw\")],\n      latin: [createFb(\"PLYyq1j1v4R5R20X-bepkF5V66hBWe1a-r\", \"Ritmos Latinos\", \"C7vfCJTQ-rw\")],\n      party: [createFb(\"PL7NXvXjIf-gGqSsswXm7-N0BsiW61wJzB\", \"Party Mix\", \"n6N1_sxlBU8\")]\n    });';
  c = c.substring(0, c3) + repl2 + c.substring(c5);
}
fs.writeFileSync('server.ts', c); console.log('Patched server.ts')